service: drone

frameworkVersion: ">=1.4.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 2048
  timeout: 30
  region: eu-west-1

functions:
  takeoff:
    handler: handler.takeoff
    events:
      - alexaSkill
